#!/bin/sh
. ../config/env

export TF_VAR_region=$REGION
export TF_VAR_domain=$DOMAIN
export TF_VAR_api_token=$(cat ~/.do-token)
export TF_VAR_servers=$SERVERS
export TF_VAR_server_size=$SERVER_SIZE
export TF_VAR_ip_int_prefix=$IP_INT_PREFIX

terraform \
  "$@"
